server:
  ssl:
    key-store: classpath:ssl/keystore_server.p12
    key-store-password: 123456
    key-store-type: pkcs12
    key-alias: keystore_server
    key-password: 123456
    enabled: true
  #    client-auth: need
  port: 8443