spring:
  application:
    name: demo-service

---

spring:
  profiles: service_ru
server:
  port: 9002
  servlet:
    context-path: /stub

---

spring:
  profiles: service_com
server:
  port: 9001
  servlet:
    context-path: /stub